### ISSUE TITLE
Uploaded text/csv mimetype

### ISSUE THREAD

**Issue by qqmyers** [GlobalDataverseCommunityConsortium/dataverse-previewers#21]
I just uploaded a file from my Windows machine using Chrome and find that Dataverse picks up the text/csv mimetype for it instead of text/comma-separated-value. In the short term, we may want to add curl commands to register that type as well (and text/tsv? - need to check). Longer term, it might make more sense for Dataverse to normalize mimetypes.

**Comment by shlake** [comment]
Yes, the Dataverse database has contenttype="text/csv" and contenttype="text/tsv", so these file types are not being displayed per the current viewers. The database entry for ".tab" files have contenttype="text/tab-separated-values" which is defined as a previewer. 

There is no contenttype = "text/comma-separated-values" in the Dataverse database.

Suggest, remove the current "comma-separated-values" previewer line and add two previewer lines to reflect the correct Dataverse spreadsheet types (Sherry has tested these and they work):

curl -X POST -H 'Content-type: application/json' http://localhost:8080/api/admin/externalTools -d \ "{ \"displayName\":\"View Data\", \"description\":\"View the spreadsheet data.\", \"scope\":\"file\", \"type\":\"explore\", \"hasPreviewMode\":\"true\", \"toolUrl\":\"https://globaldataversecommunityconsortium.github.io/dataverse-previewers/previewers/SpreadsheetPreview.html\", \"toolParameters\": { \"queryParameters\":[ {\"fileid\":\"{fileId}\"}, {\"siteUrl\":\"{siteUrl}\"}, {\"key\":\"{apiToken}\"}, {\"datasetid\":\"{datasetId}\"}, {\"datasetversion\":\"{datasetVersion}\"}, {\"locale\":\"{localeCode}\"} ] }, \"contentType\":\"text/csv\" }"

curl -X POST -H 'Content-type: application/json' http://localhost:8080/api/admin/externalTools -d \ "{ \"displayName\":\"View Data\", \"description\":\"View the spreadsheet data.\", \"scope\":\"file\", \"type\":\"explore\", \"hasPreviewMode\":\"true\", \"toolUrl\":\"https://globaldataversecommunityconsortium.github.io/dataverse-previewers/previewers/SpreadsheetPreview.html\", \"toolParameters\": { \"queryParameters\":[ {\"fileid\":\"{fileId}\"}, {\"siteUrl\":\"{siteUrl}\"}, {\"key\":\"{apiToken}\"}, {\"datasetid\":\"{datasetId}\"}, {\"datasetversion\":\"{datasetVersion}\"}, {\"locale\":\"{localeCode}\"} ] }, \"contentType\":\"text/tsv\" }"

**Comment by qqmyers** [comment]
Thanks! QDR does have a text/comma-separated-values entry - I don't think that Dataverse changes it if your browser happens to send that type. For tabs, Dataverse reserves tab-separated-value for ingested files and will force non-ingested files to use text/tsv. So, as far as I can tell, all 4 variants might occur. I'll add the two above to the list.
