### ISSUE TITLE
The links in the guide points to the old URLs

### ISSUE THREAD

**Issue by pkiraly** [GlobalDataverseCommunityConsortium/dataverse-previewers#38]
The guide shows examples like this:

```
curl -X POST -H 'Content-type: application/json' http://localhost:8080/api/admin/externalTools -d \ "{ \"displayName\":\"Read Text\", \"description\":\"Read the text file.\", \"scope\":\"file\", \"type\":\"explore\", \"hasPreviewMode\":\"true\", \"toolUrl\":\"https://qualitativedatarepository.github.io/dataverse-previewers/previewers/TextPreview.html\", \"toolParameters\": { \"queryParameters\":[ {\"fileid\":\"{fileId}\"}, {\"siteUrl\":\"{siteUrl}\"}, {\"key\":\"{apiToken}\"}, {\"datasetid\":\"{datasetId}\"}, {\"datasetversion\":\"{datasetVersion}\"} ] }, \"contentType\":\"text/plain\" }"
```
The URL mentioned here (https://qualitativedatarepository.github.io/dataverse-previewers/previewers/) is not available anymore, and generates a 404 error message in dataverse (see https://github.com/IQSS/dataverse/issues/6616 for details).

Please update guides with the following information:

* what URL should be used for new installations
* how to modify existing Dataverse settings

**Comment by pdurbin** [comment]
As I mentioned at http://irclog.iq.harvard.edu/dataverse/2020-02-06#i_117719

https://globaldataversecommunityconsortium.github.io/dataverse-previewers/previewers/SpreadsheetPreview.html looks like a promising "toolUrl". I see signs of life there:

<img width="1357" alt="Screen Shot 2020-02-06 at 6 36 04 AM" src="https://user-images.githubusercontent.com/21006/73933725-13fa4e00-48ab-11ea-87a6-ad8c9d548726.png">

**Comment by pkiraly** [comment]
For the record:

1. replacing `https://qualitativedatarepository.github.io` to `https://globaldataversecommunityconsortium.github.io` seems to be working.

2. The update process:

a. Get the list of IDs of external tools
```
curl http://localhost:8080/api/admin/externalTools | jq .
```
It gives all the IDs of the external tools.

b. Delete external tools individually:
```
curl -X DELETE http://localhost:8080/api/admin/externalTools/1
curl -X DELETE http://localhost:8080/api/admin/externalTools/2
curl -X DELETE http://localhost:8080/api/admin/externalTools/3
curl -X DELETE http://localhost:8080/api/admin/externalTools/4
curl -X DELETE http://localhost:8080/api/admin/externalTools/5
curl -X DELETE http://localhost:8080/api/admin/externalTools/6
...
```
c. copy the curl command from the README

d. replace `https://qualitativedatarepository.github.io` to `https://globaldataversecommunityconsortium.github.io`

e. run the modified curl commands

**Comment by qqmyers** [comment]
Thanks Peter – it’s my mistake. I moved the Dataverse-previewers repository to the global consortium organization and did not realize the github.io side went away. I will update the URLs and see about a pull request to change db entries, but in the meantime I’ll try to restore the original URLs as well. The intent was to move the base repo, not to require immediate changes for people using the global URLs.

-- Jim

**Comment by qqmyers** [comment]
Closing: The updates in github and restoration of the QDR github.io site should fix this. If there are further concerns, let us know.
