### ISSUE TITLE
Separate deployment from PR branch

### ISSUE THREAD

**Issue by qqmyers** [GlobalDataverseCommunityConsortium/dataverse-previewers#40]
Right now, there is only one branch. Nominally we should distinguish between master (known good) and develop (latest with merged features that is the best target for further changes). However, with the previewers also being served 'live' via github.io, there is also a branch (currently master) that is deployed in the community. It might thus be important to separate known good from deployed, i.e. to be able to point the community to a stable version prior to deployment so that they can test, we can get consensus that deploying is OK, and then alert people when the changes are going live.

I don't know whether it would make more sense to have a 'deployed' branch for that, or to use master for that and have a 'testing' branch as the intermediate. It probably doesn't matter too much, but I'll post this as an issue to start to see if there are comments regarding what would be best practice for our case. (So if you're watching...). 

One argument that I had for 'deployed' would be just to make it clearer that merging to that branch has consequences. (Because the scripts are deployed live, we should be very restrictive on who can commit in this repo in general, but I've already proven (via glitches in setting this repo up) that an extra reminder of the live nature of this repo won't hurt.)

**Comment by pdurbin** [comment]
@qqmyers on a related note, I'm wondering if you (or others) think there would be value in tagged releases of the previewers.

**Comment by qqmyers** [comment]
@pdurbin - that seems like a good way/the right way to track what's in a deployed branch (and which release people may have downloaded). Is it just an add, or do you see it as getting rid of the need for a branch?

**Comment by pdurbin** [comment]
@qqmyers to allow installations of Dataverse to use the version of the previewers hosted on GitHub Pages, you're still going to need to designate a branch that gets pushed to GitHub Pages. Back in the day this branch had to be called `gh-pages` but these days it can me any branch you want. For example, for the GitHub Pages site at https://iqss.github.io/dataverse-installations/ I'm deploying from the "master" branch. Here's how https://github.com/IQSS/dataverse-installations/settings looks:

![Screen Shot 2020-02-12 at 12 22 11 PM](https://user-images.githubusercontent.com/21006/74360195-a2327080-4d92-11ea-800e-b208df1e1eba.png)

But yeah, if wanted the ability to merge pull requests into a new `develop` branch and then later merge `develop` into `master` (or `gh-pages` or whatever), that would allow you to decide (by merging into `master` the timing of when to deploy into production (GitHub Pages).

Versioned releases are separate. I can open a new GitHub issue for that if you think they're valuable. I guess I was thinking we could say something like "version x of the previewers supports the following new file formats: x, y, z." Stuff like that.

I hope this makes sense. I'm happy to talk it out in chat if you want. 😄

**Comment by qqmyers** [comment]
@pdurbin - right - just wanted to make sure you thought version tags were separate. I don't think we need a separate issue at this point.

**Comment by pdurbin** [comment]
Yeah, it just felt related. Sorry for muddying the waters. 😄 🐳

**Comment by qqmyers** [comment]
FWIW - just tried creating a deploy branch and could not get github to show it as a potential source under settings, so I switched to creating a develop branch. So
master - what's deployed through globaldataversecommunityconsortium.github.io
develop - where PRs should be directed, where we'll integrate and test before pushing things out farther (with process/community approval mechanism tbd)

Also - tagged the current as v1.0 since there being used now and do what they are supposed to.

**Comment by qqmyers** [comment]
Closing: created develop branch and added a v1.0 tag
