### ISSUE TITLE
Resource URLs are hard-coded

### ISSUE THREAD

**Issue by kaitlinnewson** [GlobalDataverseCommunityConsortium/dataverse-previewers#51]
When preparing to change our local URL for the previewers application, we noticed that the resource URLs are hardcoded in the files, e.g.: 

`<script type="text/javascript" src="/dataverse-previewers/previewers/js/xss.js"></script>`

To fix this in our install, we changed URLs to be relative instead, e.g.:

`<script type="text/javascript" src="js/xss.js"></script>`

I'm happy to make a PR to change this so others can use flexible URLs for their own apps, but wanted to make sure there weren't any issues with this change before doing so.

**Comment by qqmyers** [comment]
I don't see any reason to keep them as is and some (e.g. scripts in lib/*) are already relative, so +1 for a PR (to the dev branch). Thanks!
