### ISSUE TITLE
Datafile description field vulnerability fix

### ISSUE THREAD

**Issue by vesaakerman** [GlobalDataverseCommunityConsortium/dataverse-previewers#54]
Sometime ago Dataverse made us aware of a `security vulnerability `related to Dataverse Previewers and the Datafile description field.  GDCC has already deployed a fix for this vulnerability. But we are running a local copy of the previewers, downloaded from https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/archive/1.1.zip.

Is there already a `.zip `file containing the fix, and where is it to `download`?

**Comment by qqmyers** [comment]
You can always go to https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers and click the 'Code'/'Download Zip' item on the page - for the master branch or the develop branch if you want newer features. That said, I'll also go ahead and add a new release for the security fix. (Also planning a new release to include changes from the develop branch soon.) Thanks!

**Comment by vesaakerman** [comment]
Ok, thanks!
I see that I can download the latest .zip from https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/archive/master.zip

**Comment by qqmyers** [comment]
v1.1.1 release made
