### ISSUE TITLE
no eyeballs by default

### ISSUE THREAD

**Issue by donsizemore** [GlobalDataverseCommunityConsortium/dataverse-previewers#56]
externaltools can have type EXPLORE, PREVIEW, or (allegedly?) both. The sample instructions in README.md set type EXPLORE, which flummoxes users who aren't used to digging in the file access drop-down to preview a file. Might I safely submit a PR to set these to either PREVIEW or BOTH, or is there a reason these default to EXPLORE?

**Comment by qqmyers** [comment]
FWIW: I think these are updated in the develop branch. Just haven't gotten to merging this and other changes (which changes the live github.io files people are using.)

**Comment by qqmyers** [comment]
fixed in v1.2+
