### ISSUE TITLE
hasPreviewMode is deprecated

### ISSUE THREAD

**Issue by donsizemore** [GlobalDataverseCommunityConsortium/dataverse-previewers#57]
related to #56, the sample dataverse-previewer tool creation commands use `hasPreviewMode`, which has been replaced by the "preview" type: https://github.com/IQSS/dataverse/releases/tag/v5.2

If my little bear brain is capable of submitting PRs to address this and #56, do let me know what you'd like done and I'll try my best.

**Comment by qqmyers** [comment]
Same here - the work is done but we need to alert people about the updates and then schedule/do the move. (We also have the move from GlobalDataverseCommunityConsortium to github.com/gdcc to do, possibly at the same time.)

**Comment by qqmyers** [comment]
fixed in v1.2
