### ISSUE TITLE
develop: extraneous backslash breaks example import commands

### ISSUE THREAD

**Issue by donsizemore** [GlobalDataverseCommunityConsortium/dataverse-previewers#58]
5.2curlcommands.md includes values such as

`"toolUrl":"https://globaldataversecommunityconsortium.github.io/dataverse-previewers/previewers/TextPreview.html\", `

and when adding each tool, the trailing backslash causes Dataverse to error out:

`{"status":"ERROR","message":"Unexpected char 111 at (line no=1, column no=228, offset=227), expecting 'r'"}`

Without this backslash, each tool can be added properly.

**Comment by qqmyers** [comment]
improved a few times and hopefully useable now (v1.2+)
