### ISSUE TITLE
Can i check if these previewers are compatible with dataverse 5.5?

### ISSUE THREAD

**Issue by ghost** [GlobalDataverseCommunityConsortium/dataverse-previewers#60]
hi,

Can i check if these previewers are compatible with dataverse 5.5? 

I have added all the previewers to my dataverse by pasting all the commands under https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers#curl-commands-to-configure-these-tools-with-your-dataverse-instance

I have also run "curl http://localhost:8080/api/admin/externalTools" to confirm they are installed.

However, when i click on "Read Document" for pdf files (see appended pic), I get this error  "Unable to retrieve metadata.errorTexterror" (see appended pic). This error also show up for all the other formats with a "preview option" i.e. images, csv, mp3 and mp4 files.
![image](https://user-images.githubusercontent.com/92703478/137664786-85616dd1-2ec9-4216-93a9-2e8f47071c8a.png)
![image](https://user-images.githubusercontent.com/92703478/137664803-05e68b79-1f02-48dc-9a6c-52f951ca6f2d.png)

In addition, my datasetdisplay (see appended pic) looks different from this example https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/blob/master/examples/datasetdisplay.png. The preview option is under the download icon instead of showing up as a button like the example.
![image](https://user-images.githubusercontent.com/92703478/137664633-3833ab58-3a5b-47a7-b10c-19bfb3b25ed5.png)

So, i would like to check if these previewers are compatible with dataverse 5.5.

Thank you in advance!

**Comment by qqmyers** [comment]
fwiw: relative paths were added in #52
