### ISSUE TITLE
Enquiry on "The dataset is too large to download." message 

### ISSUE THREAD

**Issue by debug1g** [GlobalDataverseCommunityConsortium/dataverse-previewers#63]
Hi

I have setup dataverse 5.5 using this docker compose file https://github.com/IQSS/dataverse-docker/blob/master/docker-compose.yml

I have uploaded a dataset that is only 19kb. However, I got this message  "The dataset is too large to download" in the screenshot. 

![image](https://user-images.githubusercontent.com/93647724/140040572-b1e4c32a-7b7f-4af4-8f23-3b3f196c64d3.png)

Can I check if this is the default behaviour or I have missed out any steps?  

Thank you very much

**Comment by qqmyers** [comment]
I hadn't realized you sent this to the Dataverse Previewers repository, where there are fewer people watching. This question is one that would be best to ask on the community mail list, in chat, or on the giithub.com/IQSS/dataverse repository which is for the main Dataverse software.

That said - I think 5.5 may still have shipped with the default for https://guides.dataverse.org/en/latest/installation/config.html#zipdownloadlimit at 0 bytes - if you enter a larger value, that may fix your problem. (Later versions have a more reasonable default.)

**Comment by pdurbin** [comment]
> This question is one that would be best to ask on the community mail list, in chat, or on the giithub.com/IQSS/dataverse repository which is for the main Dataverse software.

https://github.com/IQSS/dataverse-docker/issues is probably a good place to ask too, since you mentioned that repo, @debug1g 

Perhaps some extra config is done by dataverse-docker, I mean. 19 KB is awfully small though. 😄

**Comment by qqmyers** [comment]
FWIW: I think it was this: https://github.com/IQSS/dataverse/pull/8015 - went into 5.6.

**Comment by pdurbin** [comment]
@qqmyers ah yes, and https://github.com/IQSS/dataverse/issues/7932 explains quite well what the problem was:

> In v5.5, not having a ZipDownloadLimit set results in a limit of 0 being returned and that disables all Zip Downloads. The docs say there is a default limit of 100MB, but the code in SystemConfig sets the default to 0.

And yes, your suggestion above should work:

> That said - I think 5.5 may still have shipped with the default for https://guides.dataverse.org/en/latest/installation/config.html#zipdownloadlimit at 0 bytes - if you enter a larger value, that may fix your problem. (Later versions have a more reasonable default.)

Sorry for the noise. 😄

**Comment by debug1g** [comment]
thanks qqmyers and pdurbin for the advice. The problem is now fixed. thank you very much!
