### ISSUE TITLE
Support tabular file preview for more file types

### ISSUE THREAD

**Issue by philippconzett** [GlobalDataverseCommunityConsortium/dataverse-previewers#65]
As a potential dataset file downloader, I'd like file previewers to support more tabular file types, in particular the following ones:

- text/comma-separated-values, in cases where file ingest doesn't work.
- text/tab-separated-values. When testing in the Harvard Demo Dataverse, tabular-separated .tsv files are ingested and previewed as tabular files. Tabular-separated .txt files are previewed as plain text files.

See this test dataset:
[https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/H0U0FQ](https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/H0U0FQ)

**Comment by qqmyers** [comment]
The latest (v1.2+) at https://github.com/gdcc/dataverse-previewers registers the Spreadsheet viewer for text/comma-separated-values, text/csv, text/tab-separated-values, and text/tsv.
